# _config.yml
title: Islam Real Estate
description: موقع عقاري للعروض والمشاريع في العين السخنة والساحل الشمالي والقاهرة الجديدة
lang: ar
theme: null        # نخلي الثيم فاضي عادي
markdown: kramdown # الافتراضي.. تمام
plugins: []        # ما بنستخدمش إضافات خارجية

# ملفات مش لازمة للبناء
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
